DROP TABLE
database_name.public.career,
database_name.public.company_data,
database_name.public.contact,
database_name.public.education,
database_name.public.education_lvl,
database_name.public.hack,
database_name.public.hack_scope_tags,
database_name.public.hack_skill_tags,
database_name.public.interest, profile,
database_name.public.profile_role,
database_name.public.request,
database_name.public.request_status,
database_name.public.sex,
database_name.public.status_company,
database_name.public.tag,
database_name.public.career,
database_name.public.team,
database_name.public.team_profile,
database_name.public.team_status,
database_name.public.user_data
CASCADE;
